version: '3.6'
services:
  # PostgreSQL
  mysql:
    container_name: mysql
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'

  # Backend
  smart-brain-api:
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/user_management
    command: npm start
    working_dir: /usr/src/user_management
    ports:
      - '4000:4000'
